import { defineMiddleware } from 'astro:middleware';
import { SESSION_COOKIE, verifySession } from './lib/auth';

const PUBLIC_ADMIN_API = new Set(['/api/admin/login']);

/**
 * Security headers for every dynamic response. The Content-Security-Policy for
 * scripts/styles/images is generated by Astro (security.csp in astro.config.mjs);
 * `frame-ancestors` cannot be set from a <meta> tag, so it is sent here.
 */
const SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy': "frame-ancestors 'none'",
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

export const onRequest = defineMiddleware(async (context, next) => {
  const { pathname } = context.url;

  if (pathname.startsWith('/api/admin') && !PUBLIC_ADMIN_API.has(pathname)) {
    const ok = await verifySession(context.cookies.get(SESSION_COOKIE)?.value);
    if (!ok) return withHeaders(json({ error: 'Unauthorized' }, 401));
  }

  const res = withHeaders(await next());

  if (pathname.startsWith('/admin') || pathname.startsWith('/api/admin')) {
    res.headers.set('Cache-Control', 'private, no-store');
    res.headers.set('X-Robots-Tag', 'noindex, nofollow');
  }
  return res;
});

function withHeaders(res: Response): Response {
  for (const [k, v] of Object.entries(SECURITY_HEADERS)) {
    // Append (not set) so Astro's own generated CSP header, if any, is preserved.
    if (k === 'Content-Security-Policy') res.headers.append(k, v);
    else res.headers.set(k, v);
  }
  return res;
}

function json(body: unknown, status: number) {
  return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
}
